// Kalenderbrädet — grunddata: figurer, länder/miljöer, händelsetyper, tips.
// Allt är rent JavaScript utan beroenden; world.js bygger 3D av det här.
(function (root) {
  'use strict';

  const MANADER = ['Januari', 'Februari', 'Mars', 'April', 'Maj', 'Juni', 'Juli', 'Augusti', 'September', 'Oktober', 'November', 'December'];
  const VECKODAGAR = ['Mån', 'Tis', 'Ons', 'Tor', 'Fre', 'Lör', 'Sön'];

  // ------------------------------------------------------------ hudfärger, hår, kläder
  const HUDFARGER = [
    { id: 'porslin', hex: '#fbe3d4' }, { id: 'ljus', hex: '#f5cfb0' }, { id: 'persika', hex: '#eebb95' },
    { id: 'gyllene', hex: '#d9a074' }, { id: 'oliv', hex: '#c58c5c' }, { id: 'karamell', hex: '#a86a3d' },
    { id: 'kanel', hex: '#8a4f2a' }, { id: 'mocka', hex: '#5e3a20' }, { id: 'ebenholts', hex: '#3b2416' },
    { id: 'robot', hex: '#b9c4cf' }, { id: 'alien', hex: '#8fd88a' }, { id: 'zombie', hex: '#9db88f' }, { id: 'spöke', hex: '#e8ecff' },
  ];
  const HARFARGER = [
    { id: 'svart', hex: '#1b1b1f' }, { id: 'mörkbrun', hex: '#3f2a1c' }, { id: 'brun', hex: '#6b4423' }, { id: 'kastanj', hex: '#8b4a2b' },
    { id: 'röd', hex: '#b6412a' }, { id: 'blond', hex: '#e2c06a' }, { id: 'platina', hex: '#f4ecd0' }, { id: 'grå', hex: '#9a9a9a' },
    { id: 'vit', hex: '#f2f2f2' }, { id: 'blå', hex: '#3f7fd8' }, { id: 'rosa', hex: '#ee6fb0' }, { id: 'lila', hex: '#8a5bd6' }, { id: 'grön', hex: '#3fae5a' },
  ];
  const HARSTILAR = ['kort', 'lång', 'lockigt', 'knut', 'hästsvans', 'tuppkam', 'afro', 'page', 'flint', 'sidbena', 'flätor', 'kalufs'];
  const KROPPAR = [
    { id: 'kvinna', label: 'Kvinna' }, { id: 'man', label: 'Man' }, { id: 'neutral', label: 'Icke-binär' }, { id: 'barn', label: 'Barn' },
  ];
  const STILAR = ['vardag', 'sport', 'kostym', 'klänning', 'uniform', 'rock', 'pyjamas', 'rustning', 'dräkt'];
  const KLADFARGER = ['#e63946', '#f4a261', '#e9c46a', '#2a9d8f', '#264653', '#4361ee', '#7209b7', '#f72585', '#ffffff', '#111111', '#8d99ae', '#588157', '#a98467', '#00b4d8'];

  // ------------------------------------------------------------ 66 figurer att vara
  // hatt/prop bygger world.js. ansikte: 'glad' | 'cool' | 'lugn' | 'arg' | 'robot'.
  const FIGURER = [
    { id: 'lakare', namn: 'Läkare', hatt: 'stetoskop', stil: 'uniform', farg: '#ffffff', hud: 'ljus', har: 'brun', harstil: 'kort', kropp: 'kvinna', emoji: '🩺' },
    { id: 'sjukskoterska', namn: 'Sjuksköterska', hatt: 'sjukmossa', stil: 'uniform', farg: '#9dd7f5', hud: 'karamell', har: 'svart', harstil: 'knut', kropp: 'kvinna', emoji: '💉' },
    { id: 'kirurg', namn: 'Kirurg', hatt: 'munskydd', stil: 'uniform', farg: '#2a9d8f', hud: 'gyllene', har: 'mörkbrun', harstil: 'flint', kropp: 'man', emoji: '🔪' },
    { id: 'tandlakare', namn: 'Tandläkare', hatt: 'lampa', stil: 'uniform', farg: '#dff6ff', hud: 'persika', har: 'blond', harstil: 'hästsvans', kropp: 'kvinna', emoji: '🦷' },
    { id: 'astronaut', namn: 'Astronaut', hatt: 'rymdhjalm', stil: 'dräkt', farg: '#f2f2f2', hud: 'ljus', har: 'brun', harstil: 'kort', kropp: 'neutral', emoji: '🚀' },
    { id: 'kock', namn: 'Kock', hatt: 'kockmossa', stil: 'uniform', farg: '#ffffff', hud: 'oliv', har: 'svart', harstil: 'kort', kropp: 'man', emoji: '👨‍🍳' },
    { id: 'pirat', namn: 'Pirat', hatt: 'pirathatt', stil: 'rock', farg: '#4a2c2a', hud: 'gyllene', har: 'svart', harstil: 'lång', kropp: 'man', emoji: '🏴‍☠️' },
    { id: 'riddare', namn: 'Riddare', hatt: 'riddarhjalm', stil: 'rustning', farg: '#aab4c0', hud: 'ljus', har: 'brun', harstil: 'kort', kropp: 'man', emoji: '⚔️' },
    { id: 'ninja', namn: 'Ninja', hatt: 'ninjamask', stil: 'dräkt', farg: '#111111', hud: 'gyllene', har: 'svart', harstil: 'kort', kropp: 'neutral', emoji: '🥷' },
    { id: 'robot', namn: 'Robot', hatt: 'antenn', stil: 'rustning', farg: '#8d99ae', hud: 'robot', har: 'grå', harstil: 'flint', kropp: 'neutral', ansikte: 'robot', emoji: '🤖' },
    { id: 'viking', namn: 'Viking', hatt: 'hornhjalm', stil: 'rock', farg: '#7f5539', hud: 'ljus', har: 'blond', harstil: 'flätor', kropp: 'man', emoji: '🪓' },
    { id: 'kung', namn: 'Kung', hatt: 'krona', stil: 'rock', farg: '#7209b7', hud: 'persika', har: 'grå', harstil: 'kort', kropp: 'man', emoji: '👑' },
    { id: 'drottning', namn: 'Drottning', hatt: 'krona', stil: 'klänning', farg: '#c9184a', hud: 'kanel', har: 'svart', harstil: 'knut', kropp: 'kvinna', emoji: '👸' },
    { id: 'prinsessa', namn: 'Prinsessa', hatt: 'tiara', stil: 'klänning', farg: '#f9c6e0', hud: 'ljus', har: 'blond', harstil: 'lång', kropp: 'kvinna', emoji: '🎀' },
    { id: 'prins', namn: 'Prins', hatt: 'liten_krona', stil: 'kostym', farg: '#4361ee', hud: 'mocka', har: 'svart', harstil: 'kort', kropp: 'man', emoji: '🤴' },
    { id: 'brandman', namn: 'Brandman', hatt: 'brandhjalm', stil: 'uniform', farg: '#e63946', hud: 'gyllene', har: 'mörkbrun', harstil: 'kort', kropp: 'man', emoji: '🚒' },
    { id: 'polis', namn: 'Polis', hatt: 'polismossa', stil: 'uniform', farg: '#264653', hud: 'oliv', har: 'svart', harstil: 'hästsvans', kropp: 'kvinna', emoji: '👮' },
    { id: 'bonde', namn: 'Bonde', hatt: 'strahatt', stil: 'vardag', farg: '#588157', hud: 'persika', har: 'kastanj', harstil: 'kort', kropp: 'man', emoji: '🌾' },
    { id: 'cowboy', namn: 'Cowboy', hatt: 'cowboyhatt', stil: 'vardag', farg: '#a98467', hud: 'gyllene', har: 'brun', harstil: 'kort', kropp: 'man', emoji: '🤠' },
    { id: 'cowgirl', namn: 'Cowgirl', hatt: 'cowboyhatt', stil: 'vardag', farg: '#bc6c25', hud: 'ljus', har: 'röd', harstil: 'flätor', kropp: 'kvinna', emoji: '🐎' },
    { id: 'detektiv', namn: 'Detektiv', hatt: 'deerstalker', stil: 'rock', farg: '#6c584c', hud: 'ljus', har: 'mörkbrun', harstil: 'kort', kropp: 'man', ansikte: 'lugn', emoji: '🔍' },
    { id: 'trollkarl', namn: 'Trollkarl', hatt: 'trollkarlshatt', stil: 'rock', farg: '#3a0ca3', hud: 'ljus', har: 'vit', harstil: 'lång', kropp: 'man', emoji: '🧙' },
    { id: 'haxa', namn: 'Häxa', hatt: 'haxhatt', stil: 'klänning', farg: '#111111', hud: 'alien', har: 'svart', harstil: 'lång', kropp: 'kvinna', emoji: '🧙‍♀️' },
    { id: 'vampyr', namn: 'Vampyr', hatt: 'cape', stil: 'kostym', farg: '#111111', hud: 'porslin', har: 'svart', harstil: 'sidbena', kropp: 'man', ansikte: 'cool', emoji: '🧛' },
    { id: 'zombie', namn: 'Zombie', hatt: 'ingen', stil: 'vardag', farg: '#6b705c', hud: 'zombie', har: 'grå', harstil: 'kalufs', kropp: 'neutral', ansikte: 'arg', emoji: '🧟' },
    { id: 'spoke', namn: 'Spöke', hatt: 'ingen', stil: 'dräkt', farg: '#e8ecff', hud: 'spöke', har: 'vit', harstil: 'flint', kropp: 'neutral', ansikte: 'lugn', emoji: '👻' },
    { id: 'superhjalte', namn: 'Superhjälte', hatt: 'cape_mask', stil: 'sport', farg: '#e63946', hud: 'karamell', har: 'svart', harstil: 'kort', kropp: 'man', emoji: '🦸' },
    { id: 'superhjaltinna', namn: 'Superhjältinna', hatt: 'cape_mask', stil: 'sport', farg: '#4361ee', hud: 'gyllene', har: 'röd', harstil: 'lång', kropp: 'kvinna', emoji: '🦸‍♀️' },
    { id: 'fotboll', namn: 'Fotbollsspelare', hatt: 'ingen', stil: 'sport', farg: '#ffd60a', hud: 'mocka', har: 'svart', harstil: 'kort', kropp: 'man', emoji: '⚽' },
    { id: 'hockey', namn: 'Hockeyspelare', hatt: 'hockeyhjalm', stil: 'sport', farg: '#0077b6', hud: 'ljus', har: 'blond', harstil: 'kalufs', kropp: 'man', emoji: '🏒' },
    { id: 'skidakare', namn: 'Skidåkare', hatt: 'skidglasogon', stil: 'sport', farg: '#f72585', hud: 'persika', har: 'brun', harstil: 'knut', kropp: 'kvinna', emoji: '⛷️' },
    { id: 'surfare', namn: 'Surfare', hatt: 'ingen', stil: 'sport', farg: '#00b4d8', hud: 'gyllene', har: 'blond', harstil: 'lång', kropp: 'man', ansikte: 'cool', emoji: '🏄' },
    { id: 'dykare', namn: 'Dykare', hatt: 'dykmask', stil: 'dräkt', farg: '#023e8a', hud: 'oliv', har: 'svart', harstil: 'kort', kropp: 'kvinna', emoji: '🤿' },
    { id: 'pilot', namn: 'Pilot', hatt: 'pilotmossa', stil: 'uniform', farg: '#1d3557', hud: 'ljus', har: 'mörkbrun', harstil: 'kort', kropp: 'man', emoji: '✈️' },
    { id: 'sjoman', namn: 'Sjöman', hatt: 'sjomansmossa', stil: 'uniform', farg: '#ffffff', hud: 'persika', har: 'svart', harstil: 'kort', kropp: 'man', emoji: '⚓' },
    { id: 'malare', namn: 'Konstnär', hatt: 'basker', stil: 'vardag', farg: '#e9c46a', hud: 'ljus', har: 'röd', harstil: 'lockigt', kropp: 'kvinna', emoji: '🎨' },
    { id: 'musiker', namn: 'Musiker', hatt: 'horlurar', stil: 'vardag', farg: '#2a9d8f', hud: 'kanel', har: 'svart', harstil: 'afro', kropp: 'man', emoji: '🎸' },
    { id: 'rockstjarna', namn: 'Rockstjärna', hatt: 'solglasogon', stil: 'rock', farg: '#111111', hud: 'ljus', har: 'lila', harstil: 'tuppkam', kropp: 'neutral', ansikte: 'cool', emoji: '🎤' },
    { id: 'dj', namn: 'DJ', hatt: 'horlurar', stil: 'sport', farg: '#7209b7', hud: 'mocka', har: 'rosa', harstil: 'kort', kropp: 'kvinna', emoji: '🎧' },
    { id: 'programmerare', namn: 'Programmerare', hatt: 'glasogon', stil: 'vardag', farg: '#264653', hud: 'ljus', har: 'brun', harstil: 'sidbena', kropp: 'man', emoji: '💻' },
    { id: 'forskare', namn: 'Forskare', hatt: 'skyddsglasogon', stil: 'uniform', farg: '#ffffff', hud: 'oliv', har: 'grå', harstil: 'kalufs', kropp: 'kvinna', emoji: '🔬' },
    { id: 'larare', namn: 'Lärare', hatt: 'glasogon', stil: 'kostym', farg: '#8d99ae', hud: 'karamell', har: 'svart', harstil: 'page', kropp: 'kvinna', emoji: '📚' },
    { id: 'student', namn: 'Student', hatt: 'studentmossa', stil: 'vardag', farg: '#ffffff', hud: 'persika', har: 'blond', harstil: 'hästsvans', kropp: 'kvinna', emoji: '🎓' },
    { id: 'farfar', namn: 'Farfar', hatt: 'keps', stil: 'vardag', farg: '#6c584c', hud: 'ljus', har: 'vit', harstil: 'flint', kropp: 'man', ansikte: 'lugn', emoji: '👴' },
    { id: 'farmor', namn: 'Farmor', hatt: 'glasogon', stil: 'klänning', farg: '#b5838d', hud: 'porslin', har: 'grå', harstil: 'knut', kropp: 'kvinna', ansikte: 'lugn', emoji: '👵' },
    { id: 'barn', namn: 'Barn', hatt: 'keps', stil: 'vardag', farg: '#f4a261', hud: 'persika', har: 'brun', harstil: 'kalufs', kropp: 'barn', emoji: '🧒' },
    { id: 'katt', namn: 'Kattdräkt', hatt: 'kattoron', stil: 'dräkt', farg: '#f4a261', hud: 'persika', har: 'brun', harstil: 'kort', kropp: 'neutral', emoji: '🐱' },
    { id: 'hund', namn: 'Hunddräkt', hatt: 'hundoron', stil: 'dräkt', farg: '#a98467', hud: 'ljus', har: 'brun', harstil: 'kort', kropp: 'neutral', emoji: '🐶' },
    { id: 'bjorn', namn: 'Björndräkt', hatt: 'bjornoron', stil: 'dräkt', farg: '#6b4423', hud: 'karamell', har: 'brun', harstil: 'kort', kropp: 'man', emoji: '🐻' },
    { id: 'drake', namn: 'Drakdräkt', hatt: 'drakhorn', stil: 'dräkt', farg: '#2d6a4f', hud: 'alien', har: 'grön', harstil: 'tuppkam', kropp: 'neutral', emoji: '🐉' },
    { id: 'alien', namn: 'Utomjording', hatt: 'antenn', stil: 'dräkt', farg: '#b5e48c', hud: 'alien', har: 'grön', harstil: 'flint', kropp: 'neutral', ansikte: 'lugn', emoji: '👽' },
    { id: 'clown', namn: 'Clown', hatt: 'clownnasa', stil: 'dräkt', farg: '#f72585', hud: 'porslin', har: 'röd', harstil: 'afro', kropp: 'neutral', emoji: '🤡' },
    { id: 'ballerina', namn: 'Ballerina', hatt: 'tiara', stil: 'klänning', farg: '#ffc8dd', hud: 'ljus', har: 'mörkbrun', harstil: 'knut', kropp: 'kvinna', emoji: '🩰' },
    { id: 'byggare', namn: 'Byggarbetare', hatt: 'bygghjalm', stil: 'uniform', farg: '#ffb703', hud: 'gyllene', har: 'brun', harstil: 'kort', kropp: 'man', emoji: '👷' },
    { id: 'tradgard', namn: 'Trädgårdsmästare', hatt: 'strahatt', stil: 'vardag', farg: '#588157', hud: 'oliv', har: 'grå', harstil: 'page', kropp: 'kvinna', emoji: '🌻' },
    { id: 'bagare', namn: 'Bagare', hatt: 'kockmossa', stil: 'uniform', farg: '#fefae0', hud: 'ljus', har: 'kastanj', harstil: 'flätor', kropp: 'kvinna', emoji: '🥐' },
    { id: 'barista', namn: 'Barista', hatt: 'basker', stil: 'vardag', farg: '#6f4e37', hud: 'mocka', har: 'svart', harstil: 'knut', kropp: 'neutral', emoji: '☕' },
    { id: 'fotograf', namn: 'Fotograf', hatt: 'kamera', stil: 'vardag', farg: '#111111', hud: 'persika', har: 'blond', harstil: 'kort', kropp: 'man', emoji: '📷' },
    { id: 'jultomte', namn: 'Jultomte', hatt: 'tomteluva', stil: 'rock', farg: '#c1121f', hud: 'porslin', har: 'vit', harstil: 'lång', kropp: 'man', emoji: '🎅' },
    { id: 'pashare', namn: 'Påskhare', hatt: 'haroron', stil: 'dräkt', farg: '#ffffff', hud: 'porslin', har: 'vit', harstil: 'kort', kropp: 'neutral', emoji: '🐰' },
    { id: 'snogubbe', namn: 'Snögubbe', hatt: 'hoghatt', stil: 'dräkt', farg: '#ffffff', hud: 'spöke', har: 'vit', harstil: 'flint', kropp: 'neutral', emoji: '⛄' },
    { id: 'pumpa', namn: 'Pumpa', hatt: 'pumpahatt', stil: 'dräkt', farg: '#f77f00', hud: 'persika', har: 'grön', harstil: 'tuppkam', kropp: 'neutral', emoji: '🎃' },
    { id: 'lopare', namn: 'Löpare', hatt: 'pannband', stil: 'sport', farg: '#06d6a0', hud: 'kanel', har: 'svart', harstil: 'kort', kropp: 'kvinna', emoji: '🏃' },
    { id: 'cyklist', namn: 'Cyklist', hatt: 'cykelhjalm', stil: 'sport', farg: '#ef476f', hud: 'ljus', har: 'brun', harstil: 'kort', kropp: 'man', emoji: '🚴' },
    { id: 'yogi', namn: 'Yogi', hatt: 'pannband', stil: 'sport', farg: '#bde0fe', hud: 'gyllene', har: 'svart', harstil: 'knut', kropp: 'kvinna', ansikte: 'lugn', emoji: '🧘' },
    { id: 'advokat', namn: 'Advokat', hatt: 'ingen', stil: 'kostym', farg: '#111111', hud: 'ebenholts', har: 'svart', harstil: 'kort', kropp: 'man', emoji: '⚖️' },
    { id: 'kvinnochef', namn: 'VD', hatt: 'glasogon', stil: 'kostym', farg: '#1d3557', hud: 'ljus', har: 'blond', harstil: 'page', kropp: 'kvinna', emoji: '💼' },
  ];

  // ------------------------------------------------------------ länder & miljöer
  // biom styr mark/himmel/rekvisita; landmarke bygger world.js; flagga = ränder [färg,...] typ 'h' | 'v' | 'kors'.
  const BIOM = {
    skog: { mark: '#5f9e4a', himmel: '#8ec9ff', dis: '#c9e7ff', rekvisita: ['gran', 'gran', 'lov', 'sten'] },
    sno: { mark: '#eef4fb', himmel: '#c7dcf0', dis: '#e8f0fa', rekvisita: ['gran_sno', 'snogubbe', 'sten', 'gran_sno'] },
    oken: { mark: '#e6c284', himmel: '#ffd9a0', dis: '#ffe7bd', rekvisita: ['kaktus', 'sten', 'kaktus', 'dyn'] },
    tropik: { mark: '#7ccf62', himmel: '#7fd3ff', dis: '#cdefff', rekvisita: ['palm', 'palm', 'blomma', 'sten'] },
    savann: { mark: '#c9b25e', himmel: '#ffcf8a', dis: '#ffe3b8', rekvisita: ['akacia', 'sten', 'gras', 'akacia'] },
    stad: { mark: '#8a8f98', himmel: '#9ec5ff', dis: '#d6e4ff', rekvisita: ['hus', 'skyskrapa', 'hus', 'lykta'] },
    berg: { mark: '#7c9a6a', himmel: '#a9d1ff', dis: '#dbe9ff', rekvisita: ['gran', 'sten', 'berg', 'sten'] },
    hav: { mark: '#f1e2b3', himmel: '#8fd3ff', dis: '#d4f0ff', rekvisita: ['palm', 'bat', 'sten', 'fyr'], vatten: true },
    tundra: { mark: '#b8c4b1', himmel: '#c9d6e3', dis: '#e3eaf0', rekvisita: ['sten', 'gran_sno', 'sten', 'igloo'] },
    sakura: { mark: '#a8d88a', himmel: '#ffd6e7', dis: '#ffe9f2', rekvisita: ['korsbar', 'korsbar', 'lykta', 'sten'] },
    regnskog: { mark: '#3e8a3a', himmel: '#9ad5c6', dis: '#c7ebe0', rekvisita: ['palm', 'lov', 'blomma', 'lov'] },
    stapp: { mark: '#b9a96b', himmel: '#bcd8ff', dis: '#e2ecff', rekvisita: ['gras', 'sten', 'jurta', 'gras'] },
    medelhav: { mark: '#c8b98a', himmel: '#7fc4ff', dis: '#d4ecff', rekvisita: ['oliv', 'cypress', 'hus_vit', 'sten'] },
    landsbygd: { mark: '#79b356', himmel: '#9dd0ff', dis: '#d8ecff', rekvisita: ['lov', 'stuga', 'gras', 'ko'] },
    vulkan: { mark: '#5a4a44', himmel: '#f2b48a', dis: '#f7cfae', rekvisita: ['sten', 'palm', 'sten', 'lava'] },
    rymd: { mark: '#1b1b30', himmel: '#05050f', dis: '#0a0a1c', rekvisita: ['sten_mane', 'krater', 'sten_mane', 'raket'], rymd: true },
  };

  const LANDER = [
    { id: 'sverige', namn: 'Sverige', biom: 'skog', landmarke: 'stuga_rod', flagga: { r: ['#006aa7', '#fecc02'], typ: 'kors' } },
    { id: 'norge', namn: 'Norge', biom: 'berg', landmarke: 'fjord', flagga: { r: ['#ba0c2f', '#00205b', '#ffffff'], typ: 'kors' } },
    { id: 'danmark', namn: 'Danmark', biom: 'landsbygd', landmarke: 'vindmolla', flagga: { r: ['#c8102e', '#ffffff'], typ: 'kors' } },
    { id: 'finland', namn: 'Finland', biom: 'skog', landmarke: 'bastu', flagga: { r: ['#ffffff', '#002f6c'], typ: 'kors' } },
    { id: 'island', namn: 'Island', biom: 'vulkan', landmarke: 'vulkan', flagga: { r: ['#02529c', '#dc1e35', '#ffffff'], typ: 'kors' } },
    { id: 'storbritannien', namn: 'Storbritannien', biom: 'stad', landmarke: 'bigben', flagga: { r: ['#012169', '#c8102e', '#ffffff'], typ: 'kors' } },
    { id: 'irland', namn: 'Irland', biom: 'landsbygd', landmarke: 'slott', flagga: { r: ['#169b62', '#ffffff', '#ff883e'], typ: 'v' } },
    { id: 'frankrike', namn: 'Frankrike', biom: 'stad', landmarke: 'eiffel', flagga: { r: ['#0055a4', '#ffffff', '#ef4135'], typ: 'v' } },
    { id: 'tyskland', namn: 'Tyskland', biom: 'skog', landmarke: 'slott', flagga: { r: ['#000000', '#dd0000', '#ffce00'], typ: 'h' } },
    { id: 'nederlanderna', namn: 'Nederländerna', biom: 'landsbygd', landmarke: 'vindmolla', flagga: { r: ['#ae1c28', '#ffffff', '#21468b'], typ: 'h' } },
    { id: 'belgien', namn: 'Belgien', biom: 'stad', landmarke: 'atomium', flagga: { r: ['#000000', '#fdda24', '#ef3340'], typ: 'v' } },
    { id: 'spanien', namn: 'Spanien', biom: 'medelhav', landmarke: 'sagrada', flagga: { r: ['#aa151b', '#f1bf00', '#aa151b'], typ: 'h' } },
    { id: 'portugal', namn: 'Portugal', biom: 'hav', landmarke: 'fyr', flagga: { r: ['#006600', '#ff0000'], typ: 'v' } },
    { id: 'italien', namn: 'Italien', biom: 'medelhav', landmarke: 'colosseum', flagga: { r: ['#009246', '#ffffff', '#ce2b37'], typ: 'v' } },
    { id: 'schweiz', namn: 'Schweiz', biom: 'berg', landmarke: 'matterhorn', flagga: { r: ['#da291c', '#ffffff'], typ: 'kors' } },
    { id: 'osterrike', namn: 'Österrike', biom: 'berg', landmarke: 'slott', flagga: { r: ['#ed2939', '#ffffff', '#ed2939'], typ: 'h' } },
    { id: 'polen', namn: 'Polen', biom: 'landsbygd', landmarke: 'slott', flagga: { r: ['#ffffff', '#dc143c'], typ: 'h' } },
    { id: 'tjeckien', namn: 'Tjeckien', biom: 'stad', landmarke: 'slott', flagga: { r: ['#ffffff', '#d7141a', '#11457e'], typ: 'h' } },
    { id: 'grekland', namn: 'Grekland', biom: 'medelhav', landmarke: 'parthenon', flagga: { r: ['#0d5eaf', '#ffffff'], typ: 'h' } },
    { id: 'kroatien', namn: 'Kroatien', biom: 'medelhav', landmarke: 'hus_vit', flagga: { r: ['#ff0000', '#ffffff', '#171796'], typ: 'h' } },
    { id: 'turkiet', namn: 'Turkiet', biom: 'medelhav', landmarke: 'moske', flagga: { r: ['#e30a17', '#ffffff'], typ: 'h' } },
    { id: 'ryssland', namn: 'Ryssland', biom: 'sno', landmarke: 'kreml', flagga: { r: ['#ffffff', '#0039a6', '#d52b1e'], typ: 'h' } },
    { id: 'ukraina', namn: 'Ukraina', biom: 'landsbygd', landmarke: 'kyrka_guld', flagga: { r: ['#0057b7', '#ffd700'], typ: 'h' } },
    { id: 'egypten', namn: 'Egypten', biom: 'oken', landmarke: 'pyramid', flagga: { r: ['#ce1126', '#ffffff', '#000000'], typ: 'h' } },
    { id: 'marocko', namn: 'Marocko', biom: 'oken', landmarke: 'moske', flagga: { r: ['#c1272d', '#006233'], typ: 'h' } },
    { id: 'kenya', namn: 'Kenya', biom: 'savann', landmarke: 'kilimanjaro', flagga: { r: ['#000000', '#bb0000', '#006600'], typ: 'h' } },
    { id: 'sydafrika', namn: 'Sydafrika', biom: 'savann', landmarke: 'taffelberg', flagga: { r: ['#007a4d', '#ffb612', '#de3831'], typ: 'h' } },
    { id: 'nigeria', namn: 'Nigeria', biom: 'regnskog', landmarke: 'hus', flagga: { r: ['#008751', '#ffffff', '#008751'], typ: 'v' } },
    { id: 'etiopien', namn: 'Etiopien', biom: 'berg', landmarke: 'kyrka_sten', flagga: { r: ['#078930', '#fcdd09', '#da121a'], typ: 'h' } },
    { id: 'tanzania', namn: 'Tanzania', biom: 'savann', landmarke: 'kilimanjaro', flagga: { r: ['#1eb53a', '#000000', '#00a3dd'], typ: 'h' } },
    { id: 'usa', namn: 'USA', biom: 'stad', landmarke: 'frihetsgudinnan', flagga: { r: ['#b22234', '#ffffff', '#3c3b6e'], typ: 'h' } },
    { id: 'kanada', namn: 'Kanada', biom: 'skog', landmarke: 'cn_tower', flagga: { r: ['#ff0000', '#ffffff', '#ff0000'], typ: 'v' } },
    { id: 'mexiko', namn: 'Mexiko', biom: 'oken', landmarke: 'pyramid_trapp', flagga: { r: ['#006847', '#ffffff', '#ce1126'], typ: 'v' } },
    { id: 'kuba', namn: 'Kuba', biom: 'tropik', landmarke: 'fyr', flagga: { r: ['#002a8f', '#ffffff', '#cb1515'], typ: 'h' } },
    { id: 'brasilien', namn: 'Brasilien', biom: 'regnskog', landmarke: 'kristus', flagga: { r: ['#009c3b', '#ffdf00', '#002776'], typ: 'h' } },
    { id: 'argentina', namn: 'Argentina', biom: 'stapp', landmarke: 'obelisk', flagga: { r: ['#74acdf', '#ffffff', '#74acdf'], typ: 'h' } },
    { id: 'chile', namn: 'Chile', biom: 'berg', landmarke: 'moai', flagga: { r: ['#ffffff', '#d52b1e'], typ: 'h' } },
    { id: 'peru', namn: 'Peru', biom: 'berg', landmarke: 'machu', flagga: { r: ['#d91023', '#ffffff', '#d91023'], typ: 'v' } },
    { id: 'colombia', namn: 'Colombia', biom: 'regnskog', landmarke: 'hus', flagga: { r: ['#fcd116', '#003893', '#ce1126'], typ: 'h' } },
    { id: 'indien', namn: 'Indien', biom: 'tropik', landmarke: 'tajmahal', flagga: { r: ['#ff9933', '#ffffff', '#138808'], typ: 'h' } },
    { id: 'kina', namn: 'Kina', biom: 'berg', landmarke: 'muren', flagga: { r: ['#de2910', '#ffde00'], typ: 'h' } },
    { id: 'japan', namn: 'Japan', biom: 'sakura', landmarke: 'torii', flagga: { r: ['#ffffff', '#bc002d', '#ffffff'], typ: 'h' } },
    { id: 'sydkorea', namn: 'Sydkorea', biom: 'stad', landmarke: 'pagod', flagga: { r: ['#ffffff', '#cd2e3a', '#0047a0'], typ: 'h' } },
    { id: 'thailand', namn: 'Thailand', biom: 'tropik', landmarke: 'tempel', flagga: { r: ['#a51931', '#f4f5f8', '#2d2a4a'], typ: 'h' } },
    { id: 'vietnam', namn: 'Vietnam', biom: 'regnskog', landmarke: 'pagod', flagga: { r: ['#da251d', '#ffff00'], typ: 'h' } },
    { id: 'indonesien', namn: 'Indonesien', biom: 'vulkan', landmarke: 'tempel', flagga: { r: ['#ff0000', '#ffffff'], typ: 'h' } },
    { id: 'filippinerna', namn: 'Filippinerna', biom: 'hav', landmarke: 'palmstrand', flagga: { r: ['#0038a8', '#ce1126', '#fcd116'], typ: 'h' } },
    { id: 'malaysia', namn: 'Malaysia', biom: 'stad', landmarke: 'petronas', flagga: { r: ['#cc0001', '#ffffff', '#010066'], typ: 'h' } },
    { id: 'singapore', namn: 'Singapore', biom: 'stad', landmarke: 'skyskrapa', flagga: { r: ['#ef3340', '#ffffff'], typ: 'h' } },
    { id: 'australien', namn: 'Australien', biom: 'hav', landmarke: 'opera', flagga: { r: ['#00008b', '#ff0000', '#ffffff'], typ: 'h' } },
    { id: 'nya_zeeland', namn: 'Nya Zeeland', biom: 'berg', landmarke: 'fjord', flagga: { r: ['#00247d', '#cc142b', '#ffffff'], typ: 'h' } },
    { id: 'mongoliet', namn: 'Mongoliet', biom: 'stapp', landmarke: 'jurta', flagga: { r: ['#c4272f', '#015197', '#c4272f'], typ: 'v' } },
    { id: 'kazakstan', namn: 'Kazakstan', biom: 'stapp', landmarke: 'jurta', flagga: { r: ['#00afca', '#fec50c'], typ: 'h' } },
    { id: 'iran', namn: 'Iran', biom: 'oken', landmarke: 'moske', flagga: { r: ['#239f40', '#ffffff', '#da0000'], typ: 'h' } },
    { id: 'saudiarabien', namn: 'Saudiarabien', biom: 'oken', landmarke: 'moske', flagga: { r: ['#006c35', '#ffffff'], typ: 'h' } },
    { id: 'forenade_arabemiraten', namn: 'Förenade Arabemiraten', biom: 'oken', landmarke: 'burj', flagga: { r: ['#00732f', '#ffffff', '#000000'], typ: 'h' } },
    { id: 'israel', namn: 'Israel', biom: 'medelhav', landmarke: 'hus_vit', flagga: { r: ['#0038b8', '#ffffff', '#0038b8'], typ: 'h' } },
    { id: 'gronland', namn: 'Grönland', biom: 'tundra', landmarke: 'igloo', flagga: { r: ['#ffffff', '#d00c33'], typ: 'h' } },
    { id: 'antarktis', namn: 'Antarktis', biom: 'tundra', landmarke: 'pingvin', flagga: { r: ['#ffffff', '#72b7e6'], typ: 'h' } },
    { id: 'nepal', namn: 'Nepal', biom: 'berg', landmarke: 'everest', flagga: { r: ['#dc143c', '#003893'], typ: 'h' } },
    { id: 'pakistan', namn: 'Pakistan', biom: 'berg', landmarke: 'moske', flagga: { r: ['#01411c', '#ffffff'], typ: 'v' } },
    { id: 'bangladesh', namn: 'Bangladesh', biom: 'regnskog', landmarke: 'hus', flagga: { r: ['#006a4e', '#f42a41'], typ: 'h' } },
    { id: 'ghana', namn: 'Ghana', biom: 'savann', landmarke: 'hus', flagga: { r: ['#ce1126', '#fcd116', '#006b3f'], typ: 'h' } },
    { id: 'madagaskar', namn: 'Madagaskar', biom: 'tropik', landmarke: 'baobab', flagga: { r: ['#ffffff', '#fc3d32', '#007e3a'], typ: 'h' } },
    { id: 'rymden', namn: 'Rymden', biom: 'rymd', landmarke: 'raket', flagga: { r: ['#0b0b2b', '#ffffff'], typ: 'h' } },
  ];

  // ------------------------------------------------------------ händelsetyper
  // Nyckelorden avgör vilken figur som ställs på dagen: "läkare" → en läkare står där.
  const HANDELSETYPER = [
    { id: 'lakare', namn: 'Läkarbesök', emoji: '🩺', figur: 'lakare', farg: '#e63946', ord: ['läkar', 'doktor', 'vårdcentral', 'sjukhus', 'mottagning', 'provtagning', 'röntgen', 'operation'] },
    { id: 'tandlakare', namn: 'Tandläkare', emoji: '🦷', figur: 'tandlakare', farg: '#48cae4', ord: ['tandläkar', 'tandhygien', 'tand'] },
    { id: 'fodelsedag', namn: 'Födelsedag', emoji: '🎂', figur: 'prinsessa', farg: '#f72585', ord: ['födelsedag', 'fyller', 'birthday', 'bday', 'kalas'] },
    { id: 'traning', namn: 'Träning', emoji: '🏋️', figur: 'lopare', farg: '#06d6a0', ord: ['gym', 'träning', 'löpning', 'springa', 'pass', 'yoga', 'simning', 'cykl', 'fotboll', 'hockey', 'padel', 'tennis'] },
    { id: 'jobb', namn: 'Jobb', emoji: '💼', figur: 'kvinnochef', farg: '#4361ee', ord: ['jobb', 'arbet', 'möte', 'skift', 'jour', 'kontor', 'deadline', 'presentation'] },
    { id: 'resa', namn: 'Resa', emoji: '✈️', figur: 'pilot', farg: '#0096c7', ord: ['resa', 'flyg', 'tåg', 'semester', 'hotell', 'utflykt', 'buss'] },
    { id: 'mat', namn: 'Mat & fika', emoji: '🍽️', figur: 'kock', farg: '#f4a261', ord: ['middag', 'lunch', 'restaurang', 'fika', 'frukost', 'brunch', 'grill', 'pizza'] },
    { id: 'fest', namn: 'Fest', emoji: '🎉', figur: 'dj', farg: '#ff006e', ord: ['fest', 'party', 'bröllop', 'firande', 'klubb', 'konsert'] },
    { id: 'skola', namn: 'Skola & studier', emoji: '📚', figur: 'larare', farg: '#8338ec', ord: ['skola', 'lektion', 'tenta', 'studie', 'plugg', 'kurs', 'föreläsning', 'prov'] },
    { id: 'familj', namn: 'Familj', emoji: '👨‍👩‍👧', figur: 'farmor', farg: '#ffb703', ord: ['familj', 'mamma', 'pappa', 'mormor', 'farmor', 'farfar', 'morfar', 'barn', 'syster', 'bror'] },
    { id: 'hem', namn: 'Hem & sysslor', emoji: '🏠', figur: 'byggare', farg: '#a98467', ord: ['städ', 'tvätt', 'handla', 'inköp', 'hantverkare', 'flytt', 'reparation', 'trädgård'] },
    { id: 'pengar', namn: 'Pengar', emoji: '💰', figur: 'advokat', farg: '#ffd60a', ord: ['räkning', 'faktura', 'lön', 'bank', 'skatt', 'betala', 'deklaration', 'hyra'] },
    { id: 'kultur', namn: 'Kultur', emoji: '🎭', figur: 'malare', farg: '#9d4edd', ord: ['bio', 'teater', 'museum', 'utställning', 'film', 'konst', 'bibliotek'] },
    { id: 'musik', namn: 'Musik', emoji: '🎵', figur: 'musiker', farg: '#2a9d8f', ord: ['musik', 'rep', 'gig', 'spelning', 'kör', 'piano', 'gitarr'] },
    { id: 'djur', namn: 'Djur', emoji: '🐾', figur: 'hund', farg: '#bc6c25', ord: ['veterinär', 'hund', 'katt', 'häst', 'ridning', 'djur'] },
    { id: 'helg', namn: 'Helgdag', emoji: '🎄', figur: 'jultomte', farg: '#c1121f', ord: ['jul', 'påsk', 'midsommar', 'nyår', 'helgdag', 'halloween', 'lucia'] },
    { id: 'halsa', namn: 'Hälsa & vila', emoji: '🧘', figur: 'yogi', farg: '#90e0ef', ord: ['sömn', 'vila', 'massage', 'spa', 'meditation', 'terapi', 'psykolog'] },
    { id: 'natur', namn: 'Natur', emoji: '🌲', figur: 'bonde', farg: '#588157', ord: ['skog', 'vandring', 'fiske', 'camping', 'skidor', 'bad', 'strand', 'promenad'] },
    { id: 'ovrigt', namn: 'Övrigt', emoji: '📌', figur: 'barn', farg: '#8d99ae', ord: [] },
  ];
  function gissaTyp(text) {
    const t = String(text || '').toLowerCase();
    for (const typ of HANDELSETYPER) for (const o of typ.ord) if (t.includes(o)) return typ.id;
    return 'ovrigt';
  }
  function typAv(id) { return HANDELSETYPER.find((t) => t.id === id) || HANDELSETYPER[HANDELSETYPER.length - 1]; }

  // ------------------------------------------------------------ dagens rekommendation
  // 70 råd om hur appen kan användas bättre. Ett nytt varje dag (dagnummer på året).
  const TIPS = [
    'Lägg in alla födelsedagar du kan komma på i dag — varje gång figuren landar på en ger den konfetti och 100 poäng.',
    'Byt till perspektivvyn och gå dag för dag med piltangenterna. Det är lättare att se veckan som en väg än som en tabell.',
    'Sätt ett klockslag på händelserna. Då sorteras de i ordning på dagens kort och du ser vad som kommer först.',
    'Skriv "läkare" i titeln så ställer sig en läkare på dagen. Samma sak med "gym", "tandläkare", "flyg" och "middag".',
    'Bocka av händelser när de är klara. Varje avbockning ger 25 poäng och håller din streak vid liv.',
    'Skapa ett konto med din e-post så följer kalendern med till mobilen. Sätt en PIN om fler delar datorn.',
    'Prova landsvyn: byt miljö till landet du ska resa till så känns resan närmare redan i planeringen.',
    'Klä figuren som ditt yrke. En figur du känner igen dig i gör att du öppnar kalendern oftare.',
    'Lutande 25-procentsvyn passar bra på en surfplatta — hela månaden ryms och brickorna är fortfarande läsbara.',
    'Använd helhetsvyn på söndagar för att titta på hela året: var är luckorna, var är det för tätt?',
    'Lägg återkommande händelser som födelsedagar med "varje år" så behöver du bara skriva dem en gång.',
    'Sätt en påminnelse på dagen innan viktiga besök: skapa en händelse "Förbered läkarbesök" dagen före.',
    'Mejla dagens plan till dig själv från dagens kort. Det blir en checklista i inkorgen.',
    'Ge varje typ av händelse ett eget yrke — då ser du på långt håll om en vecka är full av jobb eller full av fest.',
    'Håll figuren på dagens datum. Knappen "I dag" tar dig alltid tillbaka.',
    'Testa mörkt läge på kvällen. Brädet får månsken och ögonen tackar dig.',
    'Skriv korta titlar (2–4 ord). Långa titlar klipps på brickan, men hela texten finns kvar på kortet.',
    'Lägg till "vila" som en händelse också. En tom bricka är inte samma sak som en vilodag.',
    'När figuren hoppar över Start-hörnet får du månadsbonus. Planera månaden innan hoppet för full poäng.',
    'Ta en skärmbild av helhetsvyn i början av året och en i slutet. Skillnaden är din resa.',
    'Byt miljö efter årstiden: snö i januari, körsbärsblom i april, tropik i juli.',
    'Om två saker krockar samma dag, flytta den ena genom att öppna dagen och ändra datum.',
    'Använd sökrutan för att hitta alla läkarbesök i år på en gång.',
    'Exportera din kalender som fil en gång i månaden. Den ligger hos dig, inte bara på servern.',
    'Importera din Google-kalender som .ics så slipper du skriva om det som redan finns.',
    'Ställ figuren på en dag långt fram i tiden och gå baklänges. Det visar hur många dagar du har på dig.',
    'Läkarbesök: skriv vilken mottagning i beskrivningen så finns adressen där när du står i dörren.',
    'Sätt poängmål för veckan. 500 poäng är en aktiv vecka, 1000 är en riktigt bra.',
    'Låt barnen välja sin egen figur och miljö — kalendern blir deras också.',
    'Fyll i "typ" själv om gissningen blev fel. Appen lär sig inte, men den kommer ihåg ditt val.',
    'Använd toppvyn när du planerar en hel vecka; perspektivvyn när du ska leva den.',
    'Ett tomt bräde är ett ärligt bräde. Ta bort händelser som inte längre gäller.',
    'Skriv in semestern som en resa och byt miljö till landet. Räkna ner tillsammans med figuren.',
    'Om du sitter med telefonen: svep åt höger för nästa dag, vänster för föregående.',
    'Dagens kort visar poängen du kan få. Öppna det på morgonen och bestäm vad som är viktigast.',
    'Ge födelsedagar den personens namn i titeln. Konfettin är samma, men kortet blir personligt.',
    'Sätt figuren i "barn"-kropp för barnens egen kalender och spara den under en egen e-post.',
    'Använd rymden som miljö när du behöver fokus. Inga hus, inga träd, bara brädet.',
    'En streak räknas i dagar du öppnat kalendern. Att bara titta räcker för att hålla den vid liv.',
    'Titta på månadsbonusen: den växer med antalet avbockade händelser i månaden.',
    'Lägg in träningspass som återkommande varje vecka så slipper du skriva "gym" 52 gånger.',
    'Använd beskrivningsfältet för packlistor inför resor. Det syns när du öppnar dagen.',
    'Vill du ha en ren översikt? Slå av rekvisitan i inställningarna, brädet blir snabbare på gamla datorer.',
    'Kombinera händelsetyper: "Lunch med mamma" blir familj, "Lunch på jobbet" blir jobb.',
    'Byt hårfärg efter humör. Det är gratis och det syns i alla vyer.',
    'Dela din e-post med partnern så ser ni samma bräde. Den som sparar sist vinner, så spara ofta.',
    'Lägg in deadlines som "pengar"-händelser — advokaten på brickan är svår att missa.',
    'I helhetsvyn: klicka på en månad för att hoppa dit direkt.',
    'En dag med fem händelser får en liten stapel. Om stapeln är hög varje dag är det dags att säga nej till något.',
    'Gör kalendern till startsida i webbläsaren så börjar dagen med figuren, inte med inkorgen.',
    'Prova alla fyra vyerna på samma dag. Var och en visar något de andra döljer.',
    'Skriv tiden som 14:30, inte "halv tre". Då hamnar den rätt i ordningen.',
    'Kolla inställningen "ljud". Hoppen och konfettin låter — bra hemma, mindre bra på mötet.',
    'Om servern inte svarar sparas allt lokalt ändå. Det synkas när du är tillbaka på nätet.',
    'Nyårsafton: figuren hoppar från decemberbrädet till januaribrädet. Var där och se det.',
    'Lägg till "sömn" som händelse dagar efter jour. Vilan är en del av schemat.',
    'Använd samma typ för alla vårdbesök så blir sökningen "läkare" komplett.',
    'Gå igenom nästa vecka på fredag eftermiddag. Fem minuter sparar en hel måndag.',
    'Poäng är inte målet. Målet är att veta vad som händer. Poängen är bara ett sätt att komma ihåg det.',
    'Byt landmärke genom att byta land — Eiffeltornet i Frankrike, Big Ben i Storbritannien, pyramiden i Egypten.',
    'Klicka på en figur som står på en bricka så öppnas den händelsen direkt.',
    'Skriv upp vad du fick för rekommendation i går och om du följde den. Vanor byggs på så sätt.',
    'Tomma helger är också planering. Skriv "ledig" så vet familjen att det är avsiktligt.',
    'Skriv en rad i beskrivningen efter dagen om hur den blev. Kalendern blir en dagbok.',
    'Om du fyller år själv: lägg in det. Du får konfetti av din egen kalender.',
    'Håll kalendern på ett språk. Blandning gör att nyckelorden inte känns igen.',
    'Kontrollera synkstatusen längst upp: grön = sparat på servern, gul = bara lokalt.',
    'Prova att byta kropp och stil samtidigt. Vissa kombinationer (rustning + ballerina) är oväntat bra.',
    'Ett tips om dagen är lagom. Det här var dagens.',
  ];
  function dagensTips(d) {
    const dt = d || new Date();
    const start = new Date(dt.getFullYear(), 0, 0);
    const dag = Math.floor((dt - start) / 86400000);
    return { nr: dag, text: TIPS[dag % TIPS.length] };
  }

  root.KB_DATA = { MANADER, VECKODAGAR, HUDFARGER, HARFARGER, HARSTILAR, KROPPAR, STILAR, KLADFARGER, FIGURER, BIOM, LANDER, HANDELSETYPER, gissaTyp, typAv, TIPS, dagensTips };
})(typeof window !== 'undefined' ? window : globalThis);
